config/urls.py
import debug_toolbar
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap # new sitemap
from django.contrib.sitemaps.views import sitemap # new sitemap
from django.urls import path,include
from django.views.generic.base import TemplateView # new

from django.conf import settings
from django.conf.urls.static import static

from vins.models import Vin # sitemap
info_dict = {
    'queryset': Vin.objects.all(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # new
    path('accounts/', include('django.contrib.auth.urls')), # new
    
    path('vins/', include('vins.urls', namespace='vins')), # new
    
    path('', include('pages.urls')), # new , , namespace='pages'
    #path('', TemplateView.as_view(template_name='home.html'),name='home'), # new


    path('__debug__/', include(debug_toolbar.urls)),
]
urlpatterns +=[
    path('sitemap.xml', sitemap, # new
        {'sitemaps': {'blog': GenericSitemap(info_dict, priority=0.6)}},
        name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns +=[
    path('basicSW-vin.js', TemplateView.as_view(template_name='basicSW-vin.js', content_type='application/javascript'),
    name='basicSW-vin.js',
    ),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

vins/urls.py
# articles/urls.py
from django.urls import path, reverse_lazy, reverse

from . import views

"""
from vins.views import (
    VinListView, 
    VinUpdateView, 
    VinDetailView, 
    VinDeleteView, 
    VinCreateView,
    rate_image,
    AddFavoriteView,
    DeleteFavoriteView,
    CategoryDetailView,
    TagListView,
    TagDetailView,
)
"""

app_name= 'vins'

urlpatterns = [
    path('new/', views.VinCreateView.as_view(), name='vin_new'), # new
    path('<slug:slug>/edit/',views.VinUpdateView.as_view(), name='vin_edit'),     
    path('<slug:slug>/delete/',views.VinDeleteView.as_view(), name='vin_delete'), # new

    path('<slug:slug>/',views.VinDetailView.as_view(), name='vin_detail'), 
    path('', views.VinListView.as_view(), name='vin_list'),

    #path('rate/', rate_image, name='rate-view'),
]

# vins/(?P<slug>[-a-zA-Z0-9_]+)/comment/(?P<pk>[0-9]+)/delete$
urlpatterns +=[  
    path('<slug:slug>/comment/', views.CommentCreateView.as_view(), name='vin_comment_create'),
    path('comment/<int:pk>/delete',views.CommentDeleteView.as_view(), name='vin_comment_delete'),
]

urlpatterns +=[     
    path('category/', views.CategoryListView.as_view(), name='category_list'),  
    path('category/<slug:slug>/', views.CategoryDetailView.as_view(), name='category_detail'),    
]

urlpatterns +=[ 
    path('tag/', views.TagListView.as_view(), name='tag_list'), 
    path('tag/<slug:slug>/', views.TagDetailView.as_view(), name='tag_detail'),    
]

urlpatterns +=[ 
    path('<int:pk>/favorite', views.AddFavoriteView.as_view(), name='vin_favorite'),
    path('<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='vin_unfavorite'),
]


urlpatterns += [
    
    path('', views.ServiceWorker.as_view(), name="sw"),
]

templates/base.html
<!-- templates/base.html -->
{% load static %} 
{% load vins_plus %}
{% load humanize %}
<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- fav -->
<link rel="apple-touch-icon" sizes="180x180" href="{% static '/apple-touch-icon.png'  %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static '/favicon-32x32.png'  %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static '/favicon-16x16.png'  %}">
<link rel="manifest" href="{% static '/site.webmanifest' %}">
<link rel="mask-icon" href="{% static '/safari-pinned-tab.svg'  %}" color="#f80a4e">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

<title>{% block title %} Vin & Cépage App{% endblock title %}</title>


<!-- CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/base.css' %}" />

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@700&family=Playfair+Display:ital,wght@0,400;0,700;1,400;1,700&family=Roboto:ital,wght@0,300;1,300&display=swap" rel="stylesheet">


</head>

<body >
<!-- Nav -->
<nav class="navbar navbar-expand-lg navbar-light fixed-top bg-white rounded">
  <a class="navbar-brand" href="{% url 'home' %}">
    <img src="{% static '/favicon-32x32.png' %}" alt="Vins & Cépages" width="30" height="30" class="d-inline-block align-top my-logo"> Vins & Cépages
  </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">          

        <ul class="nav navbar-nav mr-auto">
            <li><a class="nav-link" href="{% url 'vins:vin_list' %}">Les vins </a></li> 
            
            {% if user.is_authenticated %} 
            <ul class="navbar-nav ml-auto">   
              <li><a class="nav-link" href="{% url 'vins:vin_new' %}">Ajoutez un vin ! </a></li>            
              <li class="nav-item">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ user.username }} </a>
                <div class="dropdown-menu dropdown-menu-lg-left" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="{% url 'password_change'%}">Change password</a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="{% url 'logout' %}?next={% url 'vins:vin_list' %}">Log Out</a>
                </div>
              </li>
            </ul>


            {% else %}
            <form class="form-inline ml-auto">
              <a href="{% url 'login' %}?next={% url 'vins:vin_list' %}" class="btn btn-outline-secondary">Log In</a>
              <a href="{% url 'signup' %}?next={% url 'login' %}" class="btn btn-outline-dark ml-2">Sign up</a>
              </form>
            {% endif %}
            

              <form class="form-inline mt-2 mt-md-0">
                  <input type="text" placeholder="Search" aria-label="Search"  name="search"
                  {% if search %} value="{{ search }}" {% endif %}
                  >
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                  <a href="{% url 'vins:vin_list' %}"><i class="fa fa-undo"></i></a>
              </form>
             

            
    </div>
</nav>




<!-- Main --> 
<main role="main" class="backImage">
  <div class="container">

  
  <div class="vin-template">
    {% block content %}
   

    {% endblock content %}
  </div>  
  
</div><!-- endContainer --> 
        
</main>


<!-- Footer --> 
<footer class="py-3 my-4">
  <ul class="nav justify-content-center border-bottom pb-3 mb-3">
    <li class="nav-item"><a href="{% url 'home' %}" class="nav-link px-2 text-muted">Home</a></li>

    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
    <li class="nav-item"><a href="{% url 'about' %}" class="nav-link px-2 text-muted">About</a></li>
    </ul>
    <p class="text-center text-muted">&copy; 2021 <a href="https://lvdesign.github.io/mylvdesign/" alt="LVdesign Studio">LVdesign Studio</a></p>
    <p class="text-center text-muted">Vins & cépages comptent {% total_vins %} vins proposés.</p>

    
</footer>




<!-- JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
<script src="{% static 'js/main.js' %}" defer></script>

<!-- JS adactio simple  -->
<script>  
  if (navigator.serviceWorker && !navigator.serviceWorker.controller) 
  { navigator.serviceWorker.register('https://vinetcepage.herokuapp.com/'); }
</script>
</body>
</html>

templates/category_detail.html
<!-- templates/article_list.html object_list -->
{% extends 'base.html' %}
{% load static %} 

{% block title %} La région {{ category.name | upper }}

{% endblock title %}


{% block content %}
  

  <div class="col-md-9 px-0">
    <h5 class="mb-0"><b>La région</b></h5>    
    <h1 class="display-1 font-italic mt-0 overF">{{ category.name | capfirst  }} </h1>
    <p class="lead my-3 fond-blanc-bg">{{ category.description_cat | safe }}</p>
  </div>


<!-- liste des vins  par cat -->
<div class="category-entry mt-4"> 
  <h5><b>Les vins du sites :</b></h5>
        <div class="row">          
          {% for cat in category.categories.all %}  
          <div class="col-sm media mb-3"> 
            <img class="align-self-start mr-2 myImages" src="https://res.cloudinary.com/lvcloud/image/upload/v1624885333/{{ cat.image }}" alt="" width=50 >

            <h3 property="v:name" class="entry-title fn fond-blanc-bg"> <a href="{%  url 'vins:vin_detail' cat.slug %}">{{ cat.slug}}</a></h3>        
          </div>
          {% if not foorloop.last%}{% endif %}
          {% endfor %}    
      </div>
</div>

<!-- categories liste -->
{% load vins_plus %}
<div class="list-group category mt-4">
  <h5><b>Liste des categories :</b></h5>
    {% get_category_list %} 
</div>


<!-- Retour liste -->    
<div class="mt-4">
    <a href="{% url 'vins:vin_list' %}" class="btn btn-light"> Retour aux vins </a>
</div>

{% endblock %}

templates/cepage.html
<!-- templates/article_list.html object_list -->
{% extends 'base.html' %}


{% block title %} Cepages

{% endblock title %}


{% block content %}

<h1>Author List</h1>



        
{% endblock %}

templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block title %} - Home {% endblock title %}


{% block content %}   


<div class="row ">

  <div class="col-sm mb-5">
    <h1 class="newH1">Vins & Cépages</h1>
    <h2 class="mt-4"><em><b>Le vin a de l'esprit !</b></em></h2>    
  </div>

  <div class="col-sm">
      <h2 class="home-bg">Tous les vins</h2>
        <p><b>Accedez à la liste complete des vins du site "Vin & Cépage" </b> </p>
        <p><a class="btn btn-outline-secondary" href="{% url 'vins:vin_list' %}"
            role="button">Liste des vins</a></p>         
  </div>
    

  <div class="col-sm">
        <h2 class="Ital-Play-Font">Derniers vins…</h2>
        {% if images %}
        <div id="my_rotator" >
            {% for vin in images %}
            <figure>
                <img src="https://res.cloudinary.com/lvcloud/image/upload/v1624885333/{{ vin.image }}" alt="{{ vin.title }}" class="myImages borderImage" height="300" />
                <figcaption class="figure-caption" ><b> <a href="{{ vin.get_absolute_url }}" >{{ vin.title }} </a></b></figcaption>
            </figure>          
        {% endfor %}
        </div>
        {% endif %}
  </div>
      
  <div class="col-sm col-sm-3">
        <h2>Tendances <br>Vin & Cépage</h2>
        <a class="twitter-timeline" href="https://twitter.com/CepageVin?ref_src=twsrc%5Etfw">Tweets by CepageVin</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>


   





</div><!-- END ROW -->

{% endblock content %}

templates/mycategory-list.html
{% if cats %}
{# cats from return #}

{% for c in cats %}
<a href="{% url 'vins:category_detail'  c.slug %}" class="color-{{ c.name }} cat-block" title="{{ c.name }}">
    {{ c.name| capfirst}}
</a>    
{% endfor %}

{% else %}
<p><strong>There are no category present.</strong></p>

{% endif %}

templates/mytag-list.html
{% if tags %}

{% for t in tags %}
<a href="{% url 'vins:tag_detail'  t.slug %}" class="color-{{ t.name }} fond-blanc-bg-a"  title="{{ t.name }}">
    {{ t.name|capfirst }}
</a>    
{% endfor %}

{% else %}
<p><strong>There are no Tag present.</strong></p>

{% endif %}

templates/tag_detail.html
<!-- templates/tag_detail.html -->
{% extends 'base.html' %}

{% block title %} 
Le cépage {{ tag.name | upper }}
{% endblock title %}
{% load static %} 

{% block content %}


  <div class="col-md-9 px-0">
    <h5 class="mb-0"><b>Le cépage</b></h5>     
    <h1 class="display-1 font-italic mb-0 overF" >{{ tag.name | capfirst  }} </h1>
    <p class="lead my-3 fond-blanc-bg">{{ tag.description_tag | safe }}</p>
  </div>


  <!-- liste des vins  par tag --> 
  <div class="tag-entry mt-4">    
    <h5><b>Les vins sur le site :</b></h5>
      <div class="row">    
      {% for tag in tag.tags.all %}
      <div class="col-sm media mb-3"> 
        <img class="align-self-start mr-2 myImages" src="https://res.cloudinary.com/lvcloud/image/upload/v1624885333/{{ tag.image }}" alt="" width=50 >  
        <h3 class="entry-title fn fond-blanc-bg">
          <a href="{%  url 'vins:vin_detail' tag.slug %}">{{ tag.slug }} </a>
        </h3>
      </div>    
      {% if not foorloop.last%}{% endif %}
      {% endfor %}
    </div>
  </div>

  <!-- Tags liste -->
  {% load vins_plus %}
  <div class="list-group tag mt-4">
    <h5><b>Liste des cépages : </b></h5>
    {% get_tag_list %}   
  </div>
  
  <!-- Retour liste -->
  <div class="mt-4">
    <a href="{% url 'vins:vin_list' %}" class="btn btn-light"> Retour aux vins </a>
  </div>


{% endblock content %}

templates/vin_comment_delete.html
{% extends "base.html" %}

{% block title %}Vin-Comment Delete{% endblock title %}

{% block content %}
{% load humanize %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col">
        <h2>Delete Comment</h2>
        <p>Are you sure you want to delete this comment</p>
        <p><b>{{ comment.text }} ?</b></p>

        <form action="" method="POST" >
        {% csrf_token %}
        <input type="submit"  class="btn btn-primary" value="Yes, delete.">
        <a href="{% url 'vins:vin_detail' comment.vin.slug %}" class="btn btn-secondary">Cancel</a>
        </form>

    </div>
</div>
{% endblock %}

templates/vin_detail.html
<!-- templates/article_detail.html 
https://res.cloudinary.com/lvcloud/image/upload/v1633592831/media/vinslv/basket_sjgzj9.png-->
{% extends 'base.html' %}
{% block content %}
{% load humanize %}
<div class="row">
    
    <div class="col-sm">
    <img src="https://res.cloudinary.com/lvcloud/image/upload/v1624885333/{{ vin.image }}" alt="{{ vin.title }}" class="align-self-start mr-3 myImages borderImage"   width=300 />

    </div>  
        
    <div class="col-sm media-body">
            
            <h1 class="mt-0 fond-blanc-bg fond-title-padding">{{ vin.title }}</h1>
            <p></p>
            <p class="fond-noir-bg fond-padding"><b>by {{ vin.author }}</b> | {{ vin.created | date }}</p>
            <p></p>

            <h4 class="fond-blanc-bg">{{ vin.description }}</h4>
            <p></p>

            <p class="fond-noir-bg fond-padding" ><b>Prix : </b> {{ vin.price }} €</p>
            <p></p>  
            <p class="fond-noir-bg fond-padding" ><b> Boutique : </b> {{ vin.boutique }}</p>
            <p></p>
            <p class="fond-noir-bg fond-padding"><b>Région : </b> <a class="fond-blanc-bg" href="{% url 'vins:category_detail' vin.category %}"> {{ vin.category | capfirst }} </a></p>
            <p></p>
            
            <ul class="fond-blanc-bg fond-padding">
                <li class="fond-noir-bg"><b>Cépage : </b></li>
                {% for t in vin.tag.all %}
                    <li class="fond-blanc-bg fond-padding"><a href="{% url 'vins:tag_detail' t.slug %}"> #{{ t.name | capfirst }}  </a>    </li>  
                    {% if not foorloop.last%}{% endif %}
                {% endfor %}        
            </ul>
            <p></p>
            <!-- score -->
            {% if vin.score == 1 %}
            <p class="fond-blanc-bg fond-padding" >
                <b>Like :  </b>
                <i class="fa fa-glass" aria-hidden="true"></i></p>
            {% elif vin.score == 2 %}    
            <p class="fond-blanc-bg fond-padding" >
                <b>Like :  </b> 
                <i class="fa fa-glass" aria-hidden="true"></i>
                <i class="fa fa-glass" aria-hidden="true"></i>
            </p>
            {% elif vin.score == 3 %}    
            <p class="fond-blanc-bg fond-padding" >
                <b>Like :  </b>
                <i class="fa fa-glass " aria-hidden="true"></i>
                <i class="fa fa-glass " aria-hidden="true"></i>
                <i class="fa fa-glass " aria-hidden="true"></i>
            </p>
            {% elif vin.score == 4 %}    
            <p class="fond-blanc-bg fond-padding" >
                <b>Like :  </b>
                <i class="fa fa-glass " aria-hidden="true"></i>
                <i class="fa fa-glass " aria-hidden="true"></i>
                <i class="fa fa-glass " aria-hidden="true"></i>
                <i class="fa fa-glass " aria-hidden="true"></i>
            </p>
            {% elif vin.score == 5 %}    
            <p class="fond-blanc-bg fond-padding" >
                <b>Like :  </b>  
                <i class="fa fa-glass" aria-hidden="true"></i>
                <i class="fa fa-glass" aria-hidden="true"></i>
                <i class="fa fa-glass" aria-hidden="true"></i>
                <i class="fa fa-glass" aria-hidden="true"></i>
                <i class="fa fa-glass" aria-hidden="true"></i>
            </p>
            {% else %}
            <p class="fond-blanc-bg fond-padding" ><b>Like :  </b> {{ vin.score }} <i class="fa fa-glass" aria-hidden="true"></i></p>
            {% endif %}
      
          

            {% if vin.author == user %}            
            <hr>
            <!-- auteur -->
            <p>
                <a href="{% url 'vins:vin_edit' vin.slug %}">Edit</a> |
                <a href="{% url 'vins:vin_delete' vin.slug %}">Delete</a>
            </p>
            <hr>
            {% endif %}

        <div>

        {# comment #}
        <hr class="mt-5">
        <h6>Commentaires</h6>
        
        {% for comment in comments %}        
        <ul>        
            <li class="fond-noir-bg fond-padding"><b> {{ comment.text }} </b><i>par {{ comment.author }}</i> <span><small>( {{ comment.updated_at|naturaltime }} )  </small></span>
                {% if user == comment.author %}
                <span><a href="{% url 'vins:vin_comment_delete' comment.id %}">
                    <i class="fa fa-trash"></i></a></span>
                {% endif %}
            </li>
        </ul>
        {% endfor %}

        {% if user.is_authenticated %}       
       
        {% load crispy_forms_tags %}
        <form method="post" action="{% url 'vins:vin_comment_create' vin.slug %}">
            {% csrf_token %}
            {{ comment_form|crispy }}
            
        <input type="submit" class="btn btn-dark btn-sm" value="Soumettre un commentaire (140 max.)">
        
        </form>
        </p>
        {% endif %}
        {# comment #}
            </div>

            <hr class="mb-5">
           
            <p>
                <a href="{% url 'vins:vin_list' %}" class="btn btn-light"> Retour aux vins </a>
            </p>
         
        </div> 

        

        

       
 
    
    </div>

</div>


{% endblock content %}

templates/vin_list.html
<!-- templates/article_list.html 

object_list -->
{% extends 'base.html' %}

{% block title %}Liste des Vins{% endblock title %}

{% block content %}

<div class="row align-items-start">
   
    {% if vin_list %} 
    {% for vin in vin_list %}

   <!--   col-mb-4  
col-auto mb-3
col-6 col-md-4-->
    <div class="col-auto col-md-4 mb-5">
<!--    mb-4 -->
      
        
            <div class="card-body">                
                <a href="{{ vin.get_absolute_url }}">
                        <img src="https://res.cloudinary.com/lvcloud/image/upload/v1624885333/{{ vin.image }}" 
                        alt="{{ vin.title }}"
                        width=300 height=300           
                        class="myImages img-fluid mx-auto d-block borderImage"
                        />       
                        <h5 class="mt-0 fond-blanc-bg fond-title-padding">
                            {{ vin.title }} 
                        </h5>
                </a>
               
                <p></p>
                <span class="fond-noir-bg fond-padding">
                    by {{ vin.author }} | {{ vin.created | date }}</span>
                <p></p>
                <p class="fond-noir-bg fond-padding"><b>Région : </b> <a class="fond-blanc-bg" href="{% url 'vins:category_detail' vin.category %}"> {{ vin.category | capfirst }} </a></p>              
                <p></p>                
                <ul class="fond-blanc-bg fond-padding" >
                    <li class="fond-noir-bg"><b>Cépage : </b></li>
                    {% for t in vin.tag.all %}
                    <li class="fond-blanc-bg fond-padding" > <a href="{% url 'vins:tag_detail' t.slug %}"> #{{ t.name | capfirst }}  </a> </li>     
                    {% if not foorloop.last%}{% endif %}
                    {% endfor %}
                </ul>
                <p></p>
                <p class="fond-noir-bg fond-padding" ><b>Prix : </b> {{ vin.price }} €</p>
                <p></p>
                <p class="fond-noir-bg fond-padding"><b>Boutique : </b>{{ vin.boutique }}</p>
                <p></p> 
                <!-- score -->
                {% if vin.score == 1 %}
                <p class="fond-blanc-bg fond-padding" >
                    <b>Like :  </b>
                    <i class="fa fa-glass" aria-hidden="true"></i></p>
                {% elif vin.score == 2 %}    
                <p class="fond-blanc-bg fond-padding" >
                    <b>Like :  </b> 
                    <i class="fa fa-glass" aria-hidden="true"></i>
                    <i class="fa fa-glass" aria-hidden="true"></i>
                </p>
                {% elif vin.score == 3 %}    
                <p class="fond-blanc-bg fond-padding" >
                    <b>Like :  </b>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                </p>
                {% elif vin.score == 4 %}    
                <p class="fond-blanc-bg fond-padding" >
                    <b>Like :  </b>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                    <i class="fa fa-glass " aria-hidden="true"></i>
                </p>
                {% elif vin.score == 5 %}    
                <p class="fond-blanc-bg fond-padding" >
                    <b>Like :  </b>  
                    <i class="fa fa-glass" aria-hidden="true"></i>
                    <i class="fa fa-glass" aria-hidden="true"></i>
                    <i class="fa fa-glass" aria-hidden="true"></i>
                    <i class="fa fa-glass" aria-hidden="true"></i>
                    <i class="fa fa-glass" aria-hidden="true"></i>
                </p>
                {% else %}
                <p class="fond-blanc-bg fond-padding" ><b>Like :  </b> {{ vin.score }} <i class="fa fa-glass" aria-hidden="true"></i></p>
                {% endif %}

           

            
            {% if vin.author == user %}
            <!-- auteur -->
            <hr>
            <p>
                <a href="{% url 'vins:vin_edit' vin.slug %}">Edit</a> |
                <a href="{% url 'vins:vin_delete' vin.slug %}">Delete</a>  
            </p>
            <hr>
            {% endif %}

            {% if user.is_authenticated %}
            <p></p>

            <p class="Ital-Play-Font fond-blanc-bg fond-padding">vin favori ?
             <!-- user -->
            <a href="#" onclick="favPost('{% url 'vins:vin_unfavorite' vin.id %}', {{vin.id}} );return false;" 
                {% if vin.id not in favorites %} style="display: none;" {% endif %}  id="favorite_heart_{{vin.id}}">            
                <span class="fa-stack" style="vertical-align: middle;">
                    <i class="fa fa-heart fa-stack-1x" style="color: rgb(255, 0, 0);"></i>
                    <i class="fa fa-heart-o fa-stack-1x"></i>                
                </span>
            </a>

            <a href="#" onclick="favPost('{% url 'vins:vin_favorite' vin.id %}', {{vin.id}} );return false;"
            {% if vin.id in favorites %} style="display: none;" {% endif %}  id="unfavorite_heart_{{vin.id}}">
                <span class="fa-stack" style="vertical-align: middle;">
                    <i class="fa fa-heart fa-stack-1x myheart" style="display: none; color: rgb(255, 0, 0);"></i>
                    <i class="fa fa-heart-o fa-stack-1x"></i>
                </span>
            </a>
            </p>
            {% endif %}
            <p></p>
            <p>
                <a href="{{ vin.get_absolute_url }}" class="btn btn-light">plus de détails</a>
            </p>
           
           
            
            </div><!-- End CardBody -->
        
                      
   

    </div> <!-- End col-mb-4--> 
    {% endfor %} 
<!-- AVANT si error -->
{% else %}
<!-- si error -->
<div class="col-mb-4"><p>ERROR pas de vins!!!</p></div>
<!-- End- vinList -->
{% endif %}
<!-- ENDIF IfvinList END -->


<script>
    function favPost(url, vin_id) {
        console.log('Requesting JSON');
        $.post(url, {},  function(rowz){
            console.log(url, 'finished');
            $("#unfavorite_heart_"+vin_id).toggle();
            $("#favorite_heart_"+vin_id).toggle();
        }).fail(function(xhr) {
            alert('Url failed with '+xhr.status+' '+url);
        });
    }
</script>



</div><!-- END ROW -->

{% endblock content %}